"""initial

Revision ID: ad3851e08055
Revises: 
Create Date: 2026-03-28 11:11:07.714235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad3851e08055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'collaborator', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('export_records',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('collaborator_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'cancelled', name='record_status'), nullable=False),
    sa.Column('lpco', sa.String(length=100), nullable=True),
    sa.Column('vessel', sa.String(length=150), nullable=True),
    sa.Column('booking', sa.String(length=100), nullable=True),
    sa.Column('port', sa.String(length=150), nullable=True),
    sa.Column('due_25br', sa.String(length=100), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('ddl_carga', sa.Date(), nullable=True),
    sa.Column('shipping_company', sa.String(length=150), nullable=True),
    sa.Column('etb', sa.Date(), nullable=True),
    sa.Column('et5', sa.Date(), nullable=True),
    sa.Column('services', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('map_type', sa.Enum('vegetal', 'animal', name='map_type'), nullable=True),
    sa.Column('selected_unit', sa.String(length=255), nullable=True),
    sa.Column('new_seal', sa.String(length=100), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('comex_released_date', sa.Date(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['collaborator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_client_id'), 'export_records', ['client_id'], unique=False)
    op.create_index(op.f('ix_export_records_reference'), 'export_records', ['reference'], unique=False)
    op.create_table('import_records',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('collaborator_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'cancelled', name='record_status'), nullable=False),
    sa.Column('modality', sa.Enum('maritimo', 'aereo', name='modality'), nullable=True),
    sa.Column('importer', sa.String(length=255), nullable=True),
    sa.Column('ce_mercante', sa.String(length=100), nullable=True),
    sa.Column('awb_bl', sa.String(length=100), nullable=True),
    sa.Column('di_duimp_dta', sa.String(length=100), nullable=True),
    sa.Column('numero_li', sa.String(length=100), nullable=True),
    sa.Column('dta', sa.String(length=100), nullable=True),
    sa.Column('dtc', sa.String(length=100), nullable=True),
    sa.Column('shipping_company', sa.String(length=150), nullable=True),
    sa.Column('vessel', sa.String(length=150), nullable=True),
    sa.Column('port', sa.String(length=150), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('etb', sa.Date(), nullable=True),
    sa.Column('containers', sa.Text(), nullable=True),
    sa.Column('carrier', sa.String(length=255), nullable=True),
    sa.Column('local_ioa', sa.String(length=255), nullable=True),
    sa.Column('lpco_packaging', sa.String(length=100), nullable=True),
    sa.Column('lpco_number', sa.String(length=100), nullable=True),
    sa.Column('map_type', sa.Enum('vegetal', 'animal', name='map_type'), nullable=True),
    sa.Column('map_packaging_released', sa.Boolean(), nullable=False),
    sa.Column('selected_unit', sa.String(length=255), nullable=True),
    sa.Column('cargo_presence_date', sa.Date(), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.Column('comex_informed_date', sa.Date(), nullable=True),
    sa.Column('comex_released', sa.Boolean(), nullable=False),
    sa.Column('guide_sent', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['collaborator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_records_client_id'), 'import_records', ['client_id'], unique=False)
    op.create_index(op.f('ix_import_records_reference'), 'import_records', ['reference'], unique=False)
    op.create_table('import_files',
    sa.Column('import_record_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_record_id'], ['import_records.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_import_files_import_record_id'), 'import_files', ['import_record_id'], unique=False)
    op.create_table('notes',
    sa.Column('export_record_id', sa.UUID(), nullable=True),
    sa.Column('import_record_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['export_record_id'], ['export_records.id'], ),
    sa.ForeignKeyConstraint(['import_record_id'], ['import_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_export_record_id'), 'notes', ['export_record_id'], unique=False)
    op.create_index(op.f('ix_notes_import_record_id'), 'notes', ['import_record_id'], unique=False)
    op.create_table('update_history',
    sa.Column('export_record_id', sa.UUID(), nullable=True),
    sa.Column('import_record_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.Enum('export', 'import_', name='record_type'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['export_record_id'], ['export_records.id'], ),
    sa.ForeignKeyConstraint(['import_record_id'], ['import_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_history_export_record_id'), 'update_history', ['export_record_id'], unique=False)
    op.create_index(op.f('ix_update_history_import_record_id'), 'update_history', ['import_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_history_import_record_id'), table_name='update_history')
    op.drop_index(op.f('ix_update_history_export_record_id'), table_name='update_history')
    op.drop_table('update_history')
    op.drop_index(op.f('ix_notes_import_record_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_export_record_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_import_files_import_record_id'), table_name='import_files')
    op.drop_table('import_files')
    op.drop_index(op.f('ix_import_records_reference'), table_name='import_records')
    op.drop_index(op.f('ix_import_records_client_id'), table_name='import_records')
    op.drop_table('import_records')
    op.drop_index(op.f('ix_export_records_reference'), table_name='export_records')
    op.drop_index(op.f('ix_export_records_client_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
